### ISSUE TITLE
Terminated due to memory pressure

### ISSUE THREAD

**Issue by malhal** [0xced/iOS-Artwork-Extractor#23] opened 2014-01-02 23:01 UTC
On iOS 7.0.4 iPod 5G

**Comment by SamusAranX** [comment] 2014-01-02 23:43
Out of curiosity, why aren't you running this in the simulator? I got everything I needed doing that.

**Comment by 0xced** [comment] 2014-01-07 09:09
This is a duplicate of #18. iOS Artwork Extractor is not meant to be run on a device.

**Closed as completed by 0xced** 2014-01-07 09:09 UTC
