### ISSUE TITLE
Crashes When Scrolling in iOS 7

### ISSUE THREAD

**Issue by DenVog** [0xced/iOS-Artwork-Extractor#21] opened 2013-10-26 17:25 UTC
On a device with iOS 7, the app will often crash when scrolling the table in the Artwork tab.

**Comment by 0xced** [comment] 2014-01-07 09:09
This is a duplicate of #18. iOS Artwork Extractor is not meant to be run on a device.

**Closed as completed by 0xced** 2014-01-07 09:09 UTC
